"""Add unique_ad_id to DBAd and update relationships

Revision ID: 721121692678
Revises: 
Create Date: 2025-06-24 10:14:41.922780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721121692678'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('unique_ad_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ads_unique_ad_id'), 'ads', ['unique_ad_id'], unique=False)
    op.create_foreign_key('ads_unique_ad_id_fkey', 'ads', 'unique_ads', ['unique_ad_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ads_unique_ad_id_fkey', 'ads', type_='foreignkey')
    op.drop_index(op.f('ix_ads_unique_ad_id'), table_name='ads')
    op.drop_column('ads', 'unique_ad_id')
    # ### end Alembic commands ###
