
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:16-alpine 
    container_name: db
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: real_estate_user
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U real_estate_user -d real_estate_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin123
      ports:
        - "5050:80"
      depends_on:
        - db
      volumes:
        - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=real-estate-cluster
      - node.name=real-estate-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped


volumes:
  db_data:
  pgadmin_data:
  elasticsearch_data: