services:
  # База данных PostgreSQL
  db:
    image: postgres:15
    container_name: estate_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - estate_network

  # Redis для кэширования и очередей
  redis:
    image: redis:7-alpine
    container_name: estate_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      - estate_network

  # Elasticsearch для поиска
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: estate_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_EXTERNAL_PORT}:9200"
      - "${ELASTICSEARCH_TRANSPORT_PORT}:9300"
    networks:
      - estate_network

  # PgAdmin для управления БД
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: estate_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - estate_network

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: estate_api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
      - SCRAPY_API_URL=${SCRAPY_API_URL}
      - PIPELINE_INTERVAL_HOURS=${PIPELINE_INTERVAL_HOURS}
      - RUN_IMMEDIATELY_ON_START=${RUN_IMMEDIATELY_ON_START}
      - SCRAPING_SOURCES=${SCRAPING_SOURCES}
      - ENABLE_SCRAPING=${ENABLE_SCRAPING}
      - ENABLE_PHOTO_PROCESSING=${ENABLE_PHOTO_PROCESSING}
      - ENABLE_DUPLICATE_PROCESSING=${ENABLE_DUPLICATE_PROCESSING}
      - ENABLE_REALTOR_DETECTION=${ENABLE_REALTOR_DETECTION}
      - ENABLE_ELASTICSEARCH_REINDEX=${ENABLE_ELASTICSEARCH_REINDEX}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:8000"
      - "80:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ./logs:/app/logs
    networks:
      - estate_network

  # Scraper сервис
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: estate_scraper
    environment:
      - SCRAPY_API_URL=${SCRAPY_API_URL}
    depends_on:
      - api
    volumes:
      - ./logs:/app/logs
      - ./backend:/app/backend
    networks:
      - estate_network



volumes:
  postgres_data:
  elasticsearch_data:

networks:
  estate_network:
    driver: bridge