# Конфигурация для Lalafo (мультикатегорийная)
base_url: "https://lalafo.kg/api/search/v3/feed/search"
source_name: "lalafo.kg"
use_playwright: true

# Настройки API
api_settings:
  url_format: "{base_url}?category_id={category_id}&expand=url&page={page}&per-page={per_page}&with_feed_banner=true"
  start_page: 1
  per_page: 20

# Категории с соответствующими рефераками
categories:
  - name: "Продажа квартир"
    category_id: 2046
    property_type: "Квартира"
    listing_type: "Продажа"
    referer: "https://lalafo.kg/kyrgyzstan/kvartiry/prodazha-kvartir"
    
  - name: "Аренда квартир"
    category_id: 2043
    property_type: "Квартира"
    listing_type: "Аренда"
    referer: "https://lalafo.kg/kyrgyzstan/kvartiry/arenda-kvartir"
    
  - name: "Продажа домов"
    category_id: 2031
    property_type: "Дом"
    listing_type: "Продажа"
    referer: "https://lalafo.kg/kyrgyzstan/doma-i-dachi/prodazha-domov"
    
  - name: "Аренда домов"
    category_id: 2032
    property_type: "Дом"
    listing_type: "Аренда"
    referer: "https://lalafo.kg/kyrgyzstan/doma-i-dachi/arenda-domov"
    
  - name: "Продажа коммерческой недвижимости"
    category_id: 2055
    property_type: "Коммерческая недвижимость"
    listing_type: "Продажа"
    referer: "https://lalafo.kg/kyrgyzstan/kommercheskaya-nedvizhimost/prodazha"
    
  - name: "Аренда коммерческой недвижимости"
    category_id: 2064
    property_type: "Коммерческая недвижимость"
    listing_type: "Аренда"
    referer: "https://lalafo.kg/kyrgyzstan/kommercheskaya-nedvizhimost/arenda"
    
  - name: "Продажа земельных участков"
    category_id: 2038
    property_type: "Земельный участок"
    listing_type: "Продажа"
    referer: "https://lalafo.kg/kyrgyzstan/zemelnye-uchastki/prodazha-zemli"
    
  - name: "Аренда земельных участков"
    category_id: 2039
    property_type: "Земельный участок"
    listing_type: "Аренда"
    referer: "https://lalafo.kg/kyrgyzstan/zemelnye-uchastki/arenda-zemli"
    
  - name: "Продажа комнат"
    category_id: 2050
    property_type: "Комната"
    listing_type: "Продажа"
    referer: "https://lalafo.kg/kyrgyzstan/komnaty/prodazha-komnat"
    
  - name: "Аренда комнат"
    category_id: 2051
    property_type: "Комната"
    listing_type: "Аренда"
    referer: "https://lalafo.kg/kyrgyzstan/komnaty/arenda-komnat"
    
  - name: "Продажа гаражей"
    category_id: 5301
    property_type: "Гараж"
    listing_type: "Продажа"
    referer: "https://lalafo.kg/kyrgyzstan/garaji/prodayu-garazh"
    
  - name: "Аренда гаражей"
    category_id: 5299
    property_type: "Гараж"
    listing_type: "Аренда"
    referer: "https://lalafo.kg/kyrgyzstan/garaji/sdayu-garazh"

# Настройки парсинга
parse_all_listings: false       # true = парсить ВСЕ объявления, false = ограничение
max_items_limit: 200         # Если parse_all_listings: false, то сколько объявлений парсить ПО КАЖДОЙ КАТЕГОРИИ

# Настройки Playwright
playwright:
  headless: true
  sleep_time: 3

# Поля API ответа (список объявлений)
api_fields:
  items_key: "items"  # Ключ массива объявлений в ответе
  item_fields:
    title: "title"
    description: "description" 
    city: "city"
    source_id: "id"  # ID объявления для детального API
    price: "price"
    currency: "currency"
    mobile: "mobile"
    created_time: "created_time"
    url: "url"
    main_image_url: "images.0.original_url"  # Первое изображение
    images: "images"  # Массив всех изображений
    district: "district"

# Настройки детального API
detail_api:
  enabled: true
  url_format: "https://lalafo.kg/api/search/v3/feed/details/{source_id}?expand=url"
  
  # Общие маппинги полей из params по id (для всех типов недвижимости)
  common_params_mapping:
    68: "furniture"      # Мебель
    69: "rooms"          # Количество комнат
    70: "area_sqm"       # Площадь (м2)
    71: "land_area_sotka" # Площадь участка (соток)
    229: "total_floors"  # Количество этажей
    357: "district"      # Район (записывается в locations)
    870: "condition"     # Коммуникации (сохраняем в condition)
    871: "heating"       # Отопление
    872: "condition"     # Ремонт
    879: "building_type" # Тип дома
    907: "building_type" # Материал (сохраняем в building_type)
  
  # Специфичные маппинги по типам недвижимости
  property_type_params_mapping:
    "Дом":
      881: "additional_features"  # Дополнительно
      945: "subletting"          # Подселение
      2149: "offer_type"         # Тип предложения
    
    "Квартира":
      920: "capacity"            # Количество мест
      927: "amenities"           # Удобства
      928: "housing_class"       # Класс жилья
      929: "accommodation_options" # Варианты размещения
      227: "pets"               # Животные
      947: "deposit"            # Депозит, сом
      948: "appliances"         # Бытовая техника
      2149: "offer_type"        # Тип предложения
    
    "Коммерческая недвижимость":
      354: "parking"            # Паркинг
      1250: "purpose"           # Назначение
      2149: "offer_type"        # Тип предложения
    
    "Комната":
      945: "subletting"         # Подселение
      946: "for_whom"           # Для кого
      2149: "offer_type"        # Тип предложения
    
    "Гараж":
      903: "height"             # Высота (м.)
      908: "additional_features" # Дополнительно
      2149: "offer_type"        # Тип предложения
    
    "Земельный участок":
      228: "purpose"            # Назначение
      868: "documents"          # Правоустанавливающие документы
      2149: "offer_type"        # Тип предложения

# Построение полного URL объявления
url_building:
  pattern: "https://lalafo.kg{url}"  # Преобразует относительный URL в абсолютный

# Обработка данных
data_processing:
  clean_html: true
  validate_required_fields: ["title", "price"]