name: "stroka"
source_name: "stroka.kg"
spider_type: "html"
parse_all_listings: false
max_items_limit: 10

base_url: "https://stroka.kg"

# Категории недвижимости с точной классификацией
categories:
  # === ПРОДАЖА ===
  - url: "/kupit-kvartiru/"
    property_type: "Квартира"
    listing_type: "Продажа"
    name: "квартиры_продажа"
    
  - url: "/kupit-dom/"
    property_type: "Дом"
    listing_type: "Продажа"
    name: "дома_продажа"
    
  - url: "/kupit-yhastok/"
    property_type: "Земельный участок"
    listing_type: "Продажа"
    name: "участки_продажа"
    
  - url: "/kupit-dachu/"
    property_type: "Дача"
    listing_type: "Продажа"
    name: "дачи_продажа"
    
  - url: "/kupit-ofis/"
    property_type: "Коммерческая недвижимость"
    listing_type: "Продажа"
    name: "офисы_продажа"
    
  - url: "/kupit-bisnes/"
    property_type: "Коммерческая недвижимость"
    listing_type: "Продажа"
    name: "бизнес_продажа"

  # === АРЕНДА ===
  - url: "/snyat-kvartiru/"
    property_type: "Квартира"
    listing_type: "Аренда"
    name: "квартиры_аренда"
    
  - url: "/snyat-dom/"
    property_type: "Дом"
    listing_type: "Аренда"
    name: "дома_аренда"
    
  - url: "/snyat-ofis/"
    property_type: "Коммерческая недвижимость"
    listing_type: "Аренда"
    name: "офисы_аренда"
    
  - url: "/podselenie/"
    property_type: "Квартира"
    listing_type: "Аренда"
    name: "подселение"
    
  - url: "/snyat-kvartiru-na-chas/"
    property_type: "Квартира"
    listing_type: "Аренда"
    name: "почасовая_аренда"
    
  - url: "/snyat-bisnes/"
    property_type: "Коммерческая недвижимость"
    listing_type: "Аренда"
    name: "бизнес_аренда"

# Настройки пагинации
pagination:
  start_page: 1
  page_url_format: "{base_url}{category_url}?page={page}"

# Селекторы для парсинга
selectors:
  ads_list: "tbody"
  ad_card: "tbody.topics-item"
  title: "td.topics-item-topic_name a::text"
  url: "td.topics-item-topic_name a::attr(href)"
  price: "td.topics-item-topic_cost::text"
  rooms: "td.topics-item-topic_rooms::text"
  area: "td.topics-item-topic_area::text"
  details:
    phone: ".topic-view-best-phone::text"
    series: ".topic-view-best-topic_series::text"
    heating: ".topic-view-best-topic_walls::text"
    floor: ".topic-view-best-topic_floor::text"
    floor_total: ".topic-view-best-topic_floor_of::text"
    furniture: ".topic-view-best-rows-item-name-furniture::text"
    repair: ".topic-view-best-rows-item-name-repair::text"
    hot_water: ".topic-view-best-rows-item-name-hot_water::text"
    gas: ".topic-view-best-rows-item-name-gas::text"
    description: "div.topic-view-body p.bb-p"
    images: ".topic-best-view-images-image-nav::attr(style)"
    created_at: ".topic-view-topic_date_create_row::text"

# Настройки запросов  
request_settings:
  delay: 2
  timeout: 30
  retries: 3
  user_agent_rotation: true

# Обработка данных
data_processing:
  ai_extraction: true  # ИИ только для извлечения данных (НЕ классификации)
  ai_classification: false  # Классификация из категорий URL
  price_cleaning: true
  description_cleaning: true

