name: house
start_urls:
  - "https://www.house.kg/kupit-kvartiru?page=1"

selectors:
  item: "div.listing"
  title: "div.top-info p.title a::text"
  link: "div.top-info p.title a::attr(href)"
  price: "div.price-addition::text"
  price_usd: "div.price::text"

pagination:
  next_page_selector: 'a.page-link[aria-label="Вперед"]::attr(href)'

max_pages: 1

detail:
  follow_link: true
  use_playwright: true
  fields:
    address: "xpath:normalize-space(//div[@class='address'])"
    offer_type: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Тип предложения')]]//div[contains(@class, 'info')])"
    series: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Серия')]]//div[contains(@class, 'info')])"
    building: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Дом')]]//div[contains(@class, 'info')])"
    floor: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Этаж')]]//div[contains(@class, 'info')])"
    area: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Площадь')]]//div[contains(@class, 'info')])"
    heating: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Отопление')]]//div[contains(@class, 'info')])"
    condition: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Состояние')]]//div[contains(@class, 'info')])"
    ceiling_height: "xpath:normalize-space(//div[contains(@class, 'info-row')][.//div[contains(@class, 'label') and contains(text(), 'Высота потолков')]]//div[contains(@class, 'info')])"
    description: "xpath:normalize-space(//div[contains(@class, 'description')]//p[contains(@class, 'comment')]//span[contains(@class, 'original')])"
    images: "xpath://img[contains(@class, 'fotorama__img')]/@src"
    phone: "xpath://a[contains(@class, 'show-number')]//div[@class='number']/text()"
