# Конфигурация для Lalafo
api_url: "https://lalafo.kg/api/search/v3/feed/search?category_id=2040&expand=url&page=1&per-page=20&with_feed_banner=true"
main_url: "https://lalafo.kg"
use_playwright: true
make_absolute_url: true
items_path: "items"

# Настройки Playwright
playwright:
  headless: true
  sleep_time: 3

# Заголовки запроса
headers:
  accept: "application/json, text/plain, */*"
  accept-language: "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
  referer: "https://lalafo.kg/kyrgyzstan/kvartiry"
  user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
  device: "pc"
  country-id: "12"
  language: "ru_RU"

# Маппинг полей: output_field: input_path
field_mapping:
  title: "title"
  description: "description" 
  city: "city"
  is_vip: "is_vip"
  price: "price"
  currency: "currency"
  mobile: "mobile"
  created_time: "created_time"
  url: "url"
  
  # Сложные поля
  main_image_url:
    type: "main_image"
    source_path: "images"
    main_field: "is_main"
    url_field: "original_url"
    
  district:
    type: "param_search"
    source_path: "params"
    target_id: 357