name: stroka
start_urls:
  - "https://stroka.kg/kupit-kvartiru/?p=1"

selectors:
  item: "tbody.topics-item"
  title: "td.topics-item-topic_name a::text"
  link: "td.topics-item-topic_name a::attr(href)"
  price: "td.topics-item-topic_cost::text"
  rooms: "td.topics-item-topic_rooms::text"
  area: "td.topics-item-topic_area::text"

pagination:
  next_page_selector: "a.paginator-item-next::attr(href)"

max_pages: 1

detail:
  follow_link: true
  use_playwright: false
  fields:
    phone: ".topic-view-best-phone::text"
    series: ".topic-view-best-topic_series::text"
    heating: ".topic-view-best-topic_walls::text"
    floor: ".topic-view-best-topic_floor::text"
    floor_total: ".topic-view-best-topic_floor_of::text"
    furniture: ".topic-view-best-rows-item-name-furniture::text"
    repair : ".topic-view-best-rows-item-name-repair::text"
    hot_water: ".topic-view-best-rows-item-name-hot_water::text"
    gas: ".topic-view-best-rows-item-name-gas::text"
    description: "div.topic-view-body p.bb-p"
    images: ".topic-best-view-images-image-nav::attr(style)"
    created_at: ".topic-view-topic_date_create_row::text"

